services:
  apache:
    build: .
    container_name: apache_server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
  
  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: tu_password_root
      MYSQL_DATABASE: miprimerachamba
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3445:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
